show tables;
set FOREIGN_KEY_CHECKS=0;
select * FROM historialactividad;
TRUNCATE historialactividad;
TRUNCATE usuario_roles;
TRUNCATE usuario;
TRUNCATE proveedor;
TRUNCATE ordenpago;
TRUNCATE detalleordenpago;
TRUNCATE retencion;
SELECT "TABLA ANTIGUA" MENSAJE;